import customtkinter as ctk 

ctk.set_appearance_mode("Dark")
ctk.set_default_color_theme("blue")
liste = ctk.CTk()
liste.geometry("500x400")
l_frame  = ctk.CTkFrame(master=liste, width=50,fg_color="#D6E8FE")
l_frame.pack(pady = 10, padx=10, fil = "both", expand=True, side='left' )
l_frame.pack_propagate(0)
label = ctk.CTkLabel(master = l_frame, text="Skander Konte", text_color="black")
label.pack(pady = 5, anchor='center')
label = ctk.CTkLabel(master = l_frame, text="Hend Haddad", text_color="black")
label.pack(pady = 5, anchor='center')


r_frame  = ctk.CTkFrame(master=liste, width=200, fg_color="#D6E8FE")
r_frame.pack(pady = 10, padx=5, fil = "both", expand=True, side='right')
r_frame.pack_propagate(0)
label = ctk.CTkLabel(master = r_frame, text="nom", text_color='black')
label.pack(pady = 2, anchor='w')
label = ctk.CTkLabel(master = r_frame, text="prenom", text_color='black' )
label.pack(pady = 2, anchor='w')
label = ctk.CTkLabel(master = r_frame, text="date de naissance", text_color='black')
label.pack(pady = 2, anchor='w')
label = ctk.CTkLabel(master = r_frame, text="telephone", text_color='black')
label.pack(pady = 2, anchor='w')
label = ctk.CTkLabel(master = r_frame, text="date de RDV", text_color='black')
label.pack(pady = 2, anchor='w')
label = ctk.CTkLabel(master = r_frame, text="description",text_color='black')
label.pack(pady = 2, anchor='w')
button = ctk.CTkButton(master = r_frame, text="modifier")
button.pack(pady = 12, padx=10)

liste.mainloop()
